sudo: false  # use containter-based infrastructure


language: groovy

jdk:
  - openjdk7

cache:
  directories:
    # - $HOME/.sdkman
    - $HOME/.m2/repository'
    - $HOME/.gvm'


#### it's the dammn expansion variable no longer works...

env:
    global
    - TZ="Australia/Hobart" JAVA_OPTS="-Xmx1G -Xms512m -XX:PermSize=64m -XX:MaxPermSize=512m"
    - GRAILS_HOME=$HOME/grails-1.3.7/
    - PATH=$PATH:$GRAILS_HOME/bin


addons:
  postgresql: "9.4"

before_install:
  # - curl -s "https://get.sdkman.io" | bash
  # - sed -i -e 's/sdkman_auto_answer.*/sdkman_auto_answer=true/g' "/home/travis/.sdkman/etc/config"
  # - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  # - ls '/home/travis/.m2/repository'
  # - find '/home/travis/.m2/repository' -type f | wc -l
  # - find $HOME/.sdkman -type f | wc -l
  # - sdk install grails 1.3.7
  # - sdk use grails 1.3.7
  - echo $GRAILS_HOME
  - echo $PATH
  - echo $JAVA_OPTS
  - wget 'https://github.com/grails/grails-core/releases/download/v1.3.7/grails-1.3.7.zip' -O $HOME/grails-1.3.7.zip
  - unzip -q -d $HOME grails-1.3.7.zip
  # - cd $HOME && pwd && unzip $HOME/grails-1.3.7.zip



before_script:
  - ./init_test_db.sh

script:
  - ls /home/travis/build/aodn/aatams
  - $GRAILS_HOME/bin/grails test-app --echoOut
  - $GRAILS_HOME/bin/grails prod war

