sudo: false  # use containter-based infrastructure


language: groovy

jdk:
  - openjdk7

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gvm'

env:
    global
    - TZ="Australia/Hobart" JAVA_OPTS="-Xmx1G -Xms512m -XX:PermSize=64m -XX:MaxPermSize=512m"

addons:
  postgresql: "9.4"

before_install:
  - rm -rf ~/.gvm
  - curl -s get.gvm.io > ~/install_sdkman.sh
  - chmod 775 ~/install_sdkman.sh
  - ~/install_sdkman.sh
  - echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
  - source ~/.sdkman/bin/sdkman-init.sh
  - sdk install grails 1.3.7
  - sdk use grails 1.3.7

before_script:
  - ./init_test_db.sh

script:
  - grails test-app --echoOut
  - grails prod war
